### ISSUE TITLE
Deleting content types with versioning active is not possible

### ISSUE THREAD

**Issue by biki** [notum-cz/strapi-plugin-content-versioning#107]
### Describe the bug

Trying to delete content types with versioning active fails with an internal server error. The error in the log:

```
[2023-07-27 06:42:21.766] error: Only $and, $or and $not can only be used as root level operators. Found $ne.
Error: Only $and, $or and $not can only be used as root level operators. Found $ne.
    at processWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:99:13)
    at processNested (/app/node_modules/@strapi/database/lib/query/helpers/where.js:75:12)
    at processWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:120:25)
    at /app/node_modules/@strapi/database/lib/query/helpers/where.js:67:31
    at Array.map (<anonymous>)
    at Object.processWhere (/app/node_modules/@strapi/database/lib/query/helpers/where.js:67:18)
    at Object.processState (/app/node_modules/@strapi/database/lib/query/query-builder.js:317:29)
    at Object.getKnexQuery (/app/node_modules/@strapi/database/lib/query/query-builder.js:354:12)
    at Object.execute (/app/node_modules/@strapi/database/lib/query/query-builder.js:475:25)
    at Object.findMany (/app/node_modules/@strapi/database/lib/entity-manager/index.js:200:70)
```

### Steps to reproduce the behavior

1. Create a content type with versioning enabled
2. Try to delete this content type
3. Deletion fails

### Expected behavior

The content type to be deleted

### System

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.11.7
- History plugin version: 0.4.9 
- Database: Postgres 12
- Operating system: Linux

Possible related code snippet: https://github.com/notum-cz/strapi-plugin-content-versioning/blob/28ef2552805e61767a7db52e18b6b374b107a8a2/server/services/lifecycles/beforeDelete.js#L28

**Comment by omikulcik** [comment]
Hi @biki, thank you for reporting this bug. I will try to replicate it and possibly fix it.

**Comment by omikulcik** [comment]
While examining your bug I noticed also wrong version was marked as visible upon deletion. #108 should fix it and this bug.

**Comment by biki** [comment]
Thank you!
