### ISSUE TITLE
TypeError: uuid is not a function when creating content

### ISSUE THREAD

**Issue by jordanvector** [notum-cz/strapi-plugin-content-versioning#20]
## Bug report

When trying to create any content type, we are getting a 500 error and when digging into it locally the error we are getting looks like this

### Describe the bug

```
error: uuid is not a function
TypeError: uuid is not a function
    at Object.beforeCreate (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/server/services/lifecycles/beforeCreate.js:9:30)
    at Object.beforeCreate (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@notum-cz/strapi-plugin-content-versioning/server/bootstrap.js:54:34)
    at Object.run (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/database/lib/lifecycles/index.js:57:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/database/lib/entity-manager.js:158:7)
    at async Object.create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/services/entity-service/index.js:172:18)
    at async Object.<anonymous> (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
    at async Object.create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:117:19)
    at async Object.create (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/plugin-content-manager/server/controllers/collection-types.js:85:20)
    at async returnBodyMiddleware (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async module.exports (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/plugin-content-manager/server/middlewares/routing.js:39:3)
    at async policiesMiddleware (/Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
    at async /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /Users/jordanschinella/Sites/connectedfitness/connectedfitness-v2/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
```

### Steps to reproduce the behavior

On the latest version of the plugin, try to create any content item.

### Expected behavior

Content saves as expected.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14
- NPM version: 6.14.16
- Strapi version: 4.1.7
- Database: mysql
- Operating system: alpine linux

### Additional context

removing plugin and creating content works as expected

**Comment by ridoo** [comment]
Seems the import should be updated as [described on the npmjs site of uuid](https://www.npmjs.com/package/uuid/v/8.0.0#create-version-4-random-uuids):

```js
import { v4 as uuid } from 'uuid';
```

**Comment by kaansan** [comment]
I also got this error and looks like there is no solution right now.

**Comment by martincapek** [comment]
Hi, it should be fixed in v0.4.3
